name: Matrix Demo

on: push

jobs:
  build:
    continue-on-error: true
    # using matrix to specify different node versions and os
    strategy:
      matrix:
        node-version: [12, 14, 16]
        operating-system: [ubuntu-latest, macos-latest]

        # include makes sure that node 18 is run only on ubuntu-latest
        include:
          - node-version: 18
            operating-system: ubuntu-latest

        # this is opposite of include and allows you exclude stand alone matrice
        exclude:
          - node-version: 12
            operating-system: macos-latest

    # now we can set the runner dynamically
    runs-on: ${{ matrix.operating-system }} # run this job once per value in the os field and they'll be run in parallet
    steps:
      - name: get code
        uses: actions/checkout@v3

      - name: install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.node-version}}

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build
